#include <Arduino.h>
#include "keyDefine.h"
#include "outkeytable.h"

ROMAJISEQ ROMA_A = { HID_A, 0};
ROMAJISEQ ROMA_I = { HID_I, 0};
ROMAJISEQ ROMA_U = { HID_U, 0};
ROMAJISEQ ROMA_E = { HID_E, 0};
ROMAJISEQ ROMA_O = { HID_O, 0};
ROMAJISEQ ROMA_KA = { HID_K, HID_A, 0};
ROMAJISEQ ROMA_KI = { HID_K, HID_I, 0};
ROMAJISEQ ROMA_KU = { HID_K, HID_U, 0};
ROMAJISEQ ROMA_KE = { HID_K, HID_E, 0};
ROMAJISEQ ROMA_KO = { HID_K, HID_O, 0};
ROMAJISEQ ROMA_SA = { HID_S, HID_A, 0};
ROMAJISEQ ROMA_SI = { HID_S, HID_I, 0};
ROMAJISEQ ROMA_SU = { HID_S, HID_U, 0};
ROMAJISEQ ROMA_SE = { HID_S, HID_E, 0};
ROMAJISEQ ROMA_SO = { HID_S, HID_O, 0};
ROMAJISEQ ROMA_TA = { HID_T, HID_A, 0};
ROMAJISEQ ROMA_TI = { HID_T, HID_I, 0};
ROMAJISEQ ROMA_TU = { HID_T, HID_U, 0};
ROMAJISEQ ROMA_TE = { HID_T, HID_E, 0};
ROMAJISEQ ROMA_TO = { HID_T, HID_O, 0};
ROMAJISEQ ROMA_NA = { HID_N, HID_A, 0};
ROMAJISEQ ROMA_NI = { HID_N, HID_I, 0};
ROMAJISEQ ROMA_NU = { HID_N, HID_U, 0};
ROMAJISEQ ROMA_NE = { HID_N, HID_E, 0};
ROMAJISEQ ROMA_NO = { HID_N, HID_O, 0};
ROMAJISEQ ROMA_HA = { HID_H, HID_A, 0};
ROMAJISEQ ROMA_HI = { HID_H, HID_I, 0};
ROMAJISEQ ROMA_HU = { HID_H, HID_U, 0};
ROMAJISEQ ROMA_HE = { HID_H, HID_E, 0};
ROMAJISEQ ROMA_HO = { HID_H, HID_O, 0};
ROMAJISEQ ROMA_MA = { HID_M, HID_A, 0};
ROMAJISEQ ROMA_MI = { HID_M, HID_I, 0};
ROMAJISEQ ROMA_MU = { HID_M, HID_U, 0};
ROMAJISEQ ROMA_ME = { HID_M, HID_E, 0};
ROMAJISEQ ROMA_MO = { HID_M, HID_O, 0};
ROMAJISEQ ROMA_YA = { HID_Y, HID_A, 0};
ROMAJISEQ ROMA_YU = { HID_Y, HID_U, 0};
ROMAJISEQ ROMA_YO = { HID_Y, HID_O, 0};
ROMAJISEQ ROMA_RA = { HID_R, HID_A, 0};
ROMAJISEQ ROMA_RI = { HID_R, HID_I, 0};
ROMAJISEQ ROMA_RU = { HID_R, HID_U, 0};
ROMAJISEQ ROMA_RE = { HID_R, HID_E, 0};
ROMAJISEQ ROMA_RO = { HID_R, HID_O, 0};
ROMAJISEQ ROMA_WA = { HID_W, HID_A, 0};
ROMAJISEQ ROMA_WO = { HID_W, HID_O, 0};
ROMAJISEQ ROMA_NN = { HID_N, HID_N, 0};

ROMAJISEQ ROMA_GA = { HID_G, HID_A, 0};
ROMAJISEQ ROMA_GI = { HID_G, HID_I, 0};
ROMAJISEQ ROMA_GU = { HID_G, HID_U, 0};
ROMAJISEQ ROMA_GE = { HID_G, HID_E, 0};
ROMAJISEQ ROMA_GO = { HID_G, HID_O, 0};
ROMAJISEQ ROMA_ZA = { HID_Z, HID_A, 0};
ROMAJISEQ ROMA_ZI = { HID_Z, HID_I, 0};
ROMAJISEQ ROMA_ZU = { HID_Z, HID_U, 0};
ROMAJISEQ ROMA_ZE = { HID_Z, HID_E, 0};
ROMAJISEQ ROMA_ZO = { HID_Z, HID_O, 0};
ROMAJISEQ ROMA_DA = { HID_D, HID_A, 0};
ROMAJISEQ ROMA_DI = { HID_D, HID_I, 0};
ROMAJISEQ ROMA_DU = { HID_D, HID_U, 0};
ROMAJISEQ ROMA_DE = { HID_D, HID_E, 0};
ROMAJISEQ ROMA_DO = { HID_D, HID_O, 0};
ROMAJISEQ ROMA_BA = { HID_B, HID_A, 0};
ROMAJISEQ ROMA_BI = { HID_B, HID_I, 0};
ROMAJISEQ ROMA_BU = { HID_B, HID_U, 0};
ROMAJISEQ ROMA_BE = { HID_B, HID_E, 0};
ROMAJISEQ ROMA_BO = { HID_B, HID_O, 0};
ROMAJISEQ ROMA_PA = { HID_P, HID_A, 0};
ROMAJISEQ ROMA_PI = { HID_P, HID_I, 0};
ROMAJISEQ ROMA_PU = { HID_P, HID_U, 0};
ROMAJISEQ ROMA_PE = { HID_P, HID_E, 0};
ROMAJISEQ ROMA_PO = { HID_P, HID_O, 0};
ROMAJISEQ ROMA_sA = { HID_L, HID_A, 0};
ROMAJISEQ ROMA_sI = { HID_L, HID_I, 0};
ROMAJISEQ ROMA_sU = { HID_L, HID_U, 0};
ROMAJISEQ ROMA_sE = { HID_L, HID_E, 0};
ROMAJISEQ ROMA_sO = { HID_L, HID_O, 0};
ROMAJISEQ ROMA_sYA = { HID_L, HID_Y, HID_A, 0};
ROMAJISEQ ROMA_sYU = { HID_L, HID_Y, HID_U, 0};
ROMAJISEQ ROMA_sYO = { HID_L, HID_Y, HID_O, 0};
ROMAJISEQ ROMA_sTU = { HID_L, HID_T, HID_U, 0}; // っ

ROMAJISEQ ROMA_1 = { HID_1, 0};  // ・
ROMAJISEQ ROMA_2 = { HID_2, 0};  // ・
ROMAJISEQ ROMA_3 = { HID_3, 0};  // ・
ROMAJISEQ ROMA_4 = { HID_4, 0};  // ・
ROMAJISEQ ROMA_5 = { HID_5, 0};  // ・
ROMAJISEQ ROMA_6 = { HID_6, 0};  // ・
ROMAJISEQ ROMA_7 = { HID_7, 0};  // ・
ROMAJISEQ ROMA_8 = { HID_8, 0};  // ・
ROMAJISEQ ROMA_9 = { HID_9, 0};  // ・
ROMAJISEQ ROMA_0 = { HID_0, 0};  // ・


ROMAJISEQ ROMA_ten = { HID_COMM, 0}; // 、
ROMAJISEQ ROMA_mar = { HID_DOT, 0}; // 。
ROMAJISEQ ROMA_pr = { HID_DOT, 0};  //   **eiji period

ROMAJISEQ ROMA_ng = { HID_SLA, 0};  // ・
ROMAJISEQ ROMA_ent = { HID_ENT, 0};  // [enter]
ROMAJISEQ ROMA_esc = { HID_ESC, 0};  // [esc]
ROMAJISEQ ROMA_bs = { HID_BS, 0};  // [bs]
ROMAJISEQ ROMA_tab = { HID_TAB, 0};  // [tab]
ROMAJISEQ ROMA_sp = { HID_SP, 0};  // [sp]
ROMAJISEQ ROMA_mins = {  HID_MINS, 0}; //= 0x2D;  // -
ROMAJISEQ ROMA_hat = {  HID_HAT, 0}; // = 0x2E; // ^
ROMAJISEQ ROMA_at = {  HID_AT, 0};  //= 0x2F; // @
ROMAJISEQ ROMA_lbra = {  HID_LBRA, 0}; // = 0x30; // [
ROMAJISEQ ROMA_rbra = {  HID_RBRA , 0};// = 0x32; // ]
ROMAJISEQ ROMA_semc = {  HID_SEMC, 0}; // = 0x33; // ;
ROMAJISEQ ROMA_col = {  HID_COL , 0}; //= 0x34; // :
ROMAJISEQ ROMA_zh = {  HID_zh, 0}; // = 0x35; // [zh]
ROMAJISEQ ROMA_comm = {  HID_COMM, 0};//  = 0x36; // ,
ROMAJISEQ ROMA_dot = {  HID_DOT, 0}; // = 0x37; // .
ROMAJISEQ ROMA_sla = {  HID_SLA, 0}; // = 0x38; // ・

ROMAJISEQ ROMA_VU = { HID_3, HID_0, HID_F, HID_4, HID_F5, 0}; // ウ
ROMAJISEQ ROMA_QES = { HID_addshift, HID_SLA, 0}; // ？

ROMAJISEQ ROMA_TILD = { HID_addshift, HID_HAT, 0}; // ？
ROMAJISEQ ROMA_RNDlbra = { HID_addshift, HID_8, 0}; // ？
ROMAJISEQ ROMA_RNDrbra = { HID_addshift, HID_9, 0}; // ？
ROMAJISEQ ROMA_Zsla = { HID_CAPS, HID_SLA, HID_KANA, 0}; // 
ROMAJISEQ ROMA_SQRlbra = { HID_CAPS, HID_LBRA, HID_KANA, 0}; // 
ROMAJISEQ ROMA_SQRrbra = { HID_CAPS, HID_RBRA, HID_KANA, 0}; // 

ROMAJISEQ hid2romajiNS[RomaoutLen] = {
  ROMA_U, // HID_A = 0x04;
  ROMA_HE, // HID_B = 0x05;
  ROMA_SU, // HID_C = 0x06;
  ROMA_TE, // HID_D = 0x07;
  ROMA_TA, // HID_E = 0x08;
  ROMA_KE, // HID_F = 0x09;
  ROMA_SE, // HID_G = 0x0A;
  ROMA_HA, // HID_H = 0x0B;
  ROMA_KU, // HID_I = 0x0C;
  ROMA_TO, // HID_J = 0x0D;
  ROMA_KI, // HID_K = 0x0E;
  ROMA_I, // HID_L = 0x0F;
  ROMA_SO, // HID_M = 0x10;
  ROMA_ME, // HID_N = 0x11;
  ROMA_TU, // HID_O = 0x12;
  ROMA_ten, // HID_P = 0x13;  **eiji comma
  ROMA_mar, // HID_Q = 0x14;
  ROMA_KO, // HID_R = 0x15;
  ROMA_SI, // HID_S = 0x16;
  ROMA_SA, // HID_T = 0x17;
  ROMA_TI, // HID_U = 0x18;
  ROMA_HU, // HID_V = 0x19;
  ROMA_KA, // HID_W = 0x1A;
  ROMA_HI, // HID_X = 0x1B;
  ROMA_RA, // HID_Y = 0x1C;
  ROMA_pr, // HID_Z = 0x1D;  **eiji period
  ROMA_1, // HID_1 = 0x1E;
  ROMA_2, // HID_2 = 0x1F;
  ROMA_3, // HID_3 = 0x20;
  ROMA_4, // HID_4 = 0x21;
  ROMA_5, // HID_5 = 0x22;
  ROMA_6, // HID_6 = 0x23;
  ROMA_7, // HID_7 = 0x24;
  ROMA_8, // HID_8 = 0x25;
  ROMA_9, // HID_9 = 0x26;
  ROMA_0, // HID_0 = 0x27;
  ROMA_ent, // HID_ENT = 0x28;
  ROMA_esc, // HID_ESC = 0x29;
  ROMA_bs, // HID_BS = 0x2A;
  ROMA_tab, // HID_TAB = 0x2B;
  ROMA_sp, // HID_SP = 0x2C;
  ROMA_mins, // HID_MINS = 0x2D;  // -
  ROMA_hat, // HID_HAT = 0x2E; // ^
  ROMA_ten, // HID_AT = 0x2F; // 、
  ROMA_lbra, // HID_LBRA = 0x30; // [
  ROMA_rbra, // HID_RBRA = 0x31; // ]
  ROMA_rbra, // HID_RBRA = 0x32; // ]
  ROMA_NN, // HID_SEMC = 0x33; // ;
  ROMA_col, // HID_COL = 0x34; // :
  ROMA_zh, // HID_ESC = 0x35;
  ROMA_NE, // HID_COMM = 0x36; // ,
  ROMA_HO, // HID_DOT = 0x37; // .
  ROMA_sla // HID_SLA = 0x38; // ;
};

ROMAJISEQ hid2romajiOR[RomaoutLen] = {
  ROMA_VU, // HID_A = 0x04;
  ROMA_BE, // HID_B = 0x05;
  ROMA_ZU, // HID_C = 0x06;
  ROMA_DE, // HID_D = 0x07;
  ROMA_DA, // HID_E = 0x08;
  ROMA_GE, // HID_F = 0x09;
  ROMA_ZE, // HID_G = 0x0A;
  ROMA_MI, // HID_H = 0x0B;
  ROMA_RU, // HID_I = 0x0C;
  ROMA_O, // HID_J = 0x0D;
  ROMA_NO, // HID_K = 0x0E;
  ROMA_sYO, // HID_L = 0x0F;
  ROMA_YU, // HID_M = 0x10;
  ROMA_NU, // HID_N = 0x11;
  ROMA_MA, // HID_O = 0x12;
  ROMA_sE, // HID_P = 0x13;
  ROMA_sA, // HID_Q = 0x14; --
  ROMA_GO, // HID_R = 0x15;
  ROMA_ZI, // HID_S = 0x16;
  ROMA_ZA, // HID_T = 0x17;
  ROMA_NI, // HID_U = 0x18;
  ROMA_BU, // HID_V = 0x19;
  ROMA_GA, // HID_W = 0x1A;
  ROMA_BI, // HID_X = 0x1B;
  ROMA_YO, // HID_Y = 0x1C;
  ROMA_sU, // HID_Z = 0x1D;
  ROMA_1, // HID_1 = 0x1E;
  ROMA_2, // HID_2 = 0x1F;
  ROMA_3, // HID_3 = 0x20;
  ROMA_4, // HID_4 = 0x21;
  ROMA_5, // HID_5 = 0x22;
  ROMA_SQRlbra, // HID_6 = 0x23;
  ROMA_SQRrbra, // HID_7 = 0x24;
  ROMA_RNDlbra, // HID_8 = 0x25;  (
  ROMA_RNDrbra, // HID_9 = 0x26; )
  ROMA_0, // HID_0 = 0x27;
  ROMA_ent, // HID_ENT = 0x28;
  ROMA_esc, // HID_ESC = 0x29;
  ROMA_bs, // HID_BS = 0x2A;
  ROMA_tab, // HID_TAB = 0x2B;
  ROMA_sp, // HID_SP = 0x2C;
  ROMA_mins, // HID_MINS = 0x2D;  // -
  ROMA_hat, // HID_HAT = 0x2E; // ^
  ROMA_at, // HID_AT = 0x2F; // @
  ROMA_lbra, // HID_LBRA = 0x30; // [
  ROMA_rbra, // HID_RBRA = 0x31; // ]
  ROMA_rbra, // HID_RBRA = 0x32; // ]
  ROMA_sTU, // HID_SEMC = 0x33; // ;
  ROMA_col, // HID_COL = 0x34; // :
  ROMA_zh, // HID_ESC = 0x35; ()
  ROMA_MU, // HID_COMM = 0x36; // ,
  ROMA_WA, // HID_DOT = 0x37; // .
  ROMA_sO // HID_SLA = 0x38; // 
};

ROMAJISEQ hid2romajiOL[RomaoutLen] = {
  ROMA_WO, // HID_A = 0x04;
  ROMA_sI, // HID_B = 0x05;
  ROMA_RO, // HID_C = 0x06;
  ROMA_NA, // HID_D = 0x07;
  ROMA_RI, // HID_E = 0x08;
  ROMA_sYU, // HID_F = 0x09;
  ROMA_MO, // HID_G = 0x0A;
  ROMA_BA, // HID_H = 0x0B;
  ROMA_GU, // HID_I = 0x0C;
  ROMA_DO, // HID_J = 0x0D;
  ROMA_GI, // HID_K = 0x0E;
  ROMA_PO, // HID_L = 0x0F;
  ROMA_ZO, // HID_M = 0x10;
  ROMA_PU, // HID_N = 0x11;
  ROMA_DU, // HID_O = 0x12;
  ROMA_PI, // HID_P = 0x13;
  ROMA_sA, // HID_Q = 0x14; --
  ROMA_sYA, // HID_R = 0x15;
  ROMA_A, // HID_S = 0x16;
  ROMA_RE, // HID_T = 0x17;
  ROMA_DI, // HID_U = 0x18;
  ROMA_YA, // HID_V = 0x19;
  ROMA_E, // HID_W = 0x1A;
  ROMA_mins, // HID_X = 0x1B;
  ROMA_PA, // HID_Y = 0x1C;
  ROMA_sU, // HID_Z = 0x1D;
  ROMA_QES, // HID_1 = 0x1E;
  ROMA_Zsla, // HID_2 = 0x1F;
  ROMA_TILD, // HID_3 = 0x20;
  ROMA_lbra, // HID_4 = 0x21;
  ROMA_rbra, // HID_5 = 0x22;
  ROMA_lbra, // HID_6 = 0x23;
  ROMA_rbra, // HID_7 = 0x24;
  ROMA_lbra, // HID_8 = 0x25;  ()
  ROMA_rbra, // HID_9 = 0x26; ()
  ROMA_0, // HID_0 = 0x27;
  ROMA_ent, // HID_ENT = 0x28;
  ROMA_esc, // HID_ESC = 0x29;
  ROMA_bs, // HID_BS = 0x2A;
  ROMA_tab, // HID_TAB = 0x2B;
  ROMA_sp, // HID_SP = 0x2C;
  ROMA_mins, // HID_MINS = 0x2D;  // -
  ROMA_hat, // HID_HAT = 0x2E; // ^
  ROMA_at, // HID_AT = 0x2F; // @
  ROMA_lbra, // HID_LBRA = 0x30; // [
  ROMA_rbra, // HID_RBRA = 0x31; // ]
  ROMA_rbra, // HID_RBRA = 0x32; // ]
  ROMA_sTU, // HID_SEMC = 0x33; // ;
  ROMA_col, // HID_COL = 0x34; // :
  ROMA_zh, // HID_ESC = 0x35; ()
  ROMA_PE, // HID_COMM = 0x36; // ,
  ROMA_BO, // HID_DOT = 0x37; // .
  ROMA_sO // HID_SLA = 0x38; // 
};
